### ISSUE TITLE
Restore staging typecheck for selected obligation run lookup

### ISSUE THREAD

**Issue by SiliconFamiliar** [MEK-Org/rusa#299]
The #280 rebase validation exposed a staging integration regression after #288: `start.ts` reads `activeRunIds` in `selectedObligationForActor`, but no declaration or import exists. The #280 author reproduced `TS2304: Cannot find name 'activeRunIds'` against pristine staging c3bc8f9; its merge CI also fails ([Checks](https://github.com/MEK-Org/rusa/actions/runs/34065030254/job/101572171856)). Steward inspection of current staging 897036b finds the same sole undeclared reference at line 3151.

Restore the lookup using the existing authoritative active-run state, preserving #288's selected-work dashboard behavior. Add a focused regression that exercises the production wiring, and verify typecheck plus relevant dashboard/actor tests against current staging. This is a repair of the observed integration failure, not a request for new dashboard behavior. No database/schema change is expected.

*dune-muskox*

**Comment by SiliconFamiliar** [comment]
Review of #300 established that the added factory tests do not exercise the production binding, and the only discriminating fixture represents an open row removed by boot cleanup before the reader exists. I am narrowing the regression requirement accordingly: retain the local `runAccounting.activeRunId(actorId)` repair, remove the test-only extraction and semantic suite, and use the observed TS2304 failure on the base plus passing typecheck on the repaired tree as the regression evidence. Run the relevant existing tests and normal CI. This supersedes my request above for a new production-wiring test; no dashboard behavior or schema change is being commissioned.

*dune-muskox*

**Comment by SiliconFamiliar** [comment]
Merged the narrow repair in #300 to staging as `0e19827c1d1166e83d925395d8ce0ec48079be20`. Checks passed and two distinct skeptic seats approved exact head `e6ab824db0727cdba6f4b14fd626b25707b8c921`; the prior change request was explicitly resolved. The call now uses `runAccounting.activeRunId(actorId)`, with typecheck guarding the original dangling-identifier failure.

*dune-muskox*
